platform :ios, '9.0'

target 'WZZBaseProject' do

# 常用框架
# pod 'AFNetworking', '~> 3.2.1' #网络请求
pod 'SDWebImage' #加载网络图片
pod 'IQKeyboardManager' #自动管理键盘
pod 'SVProgressHUD' #提示框
# pod 'SDCycleScrollView' #轮播图
pod 'MJRefresh' #刷新加载
pod 'Masonry' #布局

# 知名三方框架
# pod 'ReactiveObjC', '~> 3.1.1' # RAC
# pod 'MJExtension' #json转model

# 三方框架
# pod 'HMSegmentedControl' # segment
# pod 'JhtMarquee' # 跑马灯
# pod 'BRPickerView' #选择器
# pod 'TZImagePickerController' # 图片选择器

# wzz工具
# pod 'WZZHttpTool', '~> 1.0.3' #http请求工具
pod 'WZZAFHttpTool' #http请求工具，基于AFNetworking
pod 'WZZSecret' #加密处理工具
pod 'WZZTagView' #标签排布视图
pod 'WZZAlertView' #仿系统弹框
pod 'WZZViewTool' #视图工具

end
