platform :ios, '8.0'

target 'WZZBaseProject' do

# 常用框架
pod 'AFNetworking', '~> 3.2.1' #网络请求
pod 'SDWebImage', '~> 4.3.3' #加载网络图片
pod 'IQKeyboardManager', '~> 6.0.3' #自动管理键盘
pod 'SVProgressHUD', '~> 2.2.5' #提示框
pod 'SDCycleScrollView', '~> 1.75' #轮播图
pod 'MJRefresh', '~> 3.1.15.3' #刷新加载
pod 'MJExtension', '~> 3.0.13' #json转model
pod 'TOWebViewController', '~> 2.2.7' #web控制器

# wzz工具
pod 'WZZHttpTool', '~> 1.0.0' #http请求工具
pod 'WZZSecret', '~> 1.0.5' #加密处理工具

end
